name: Rust

on:
  push:
    branches: ["master", "dev", "feature/*"]
  pull_request:
    branches: ["master", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build --verbose
      - name: Build (full)
        run: cargo build --verbose --features full
      - name: Run tests
        run: cargo test --verbose
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v6
        with:
          name: debug build
          path: |
            target/debug/caffeinate2
            target/debug/caffeinate2-tray
            target/debug/caffeinate2-helper
          if-no-files-found: error
